name: Create release

on:
  workflow_dispatch:
    inputs:
      deno_version:
        description: "Deno version (e.g. v1.20.3)"
        required: false
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ github.event.inputs.deno_version || 'vx.x.x' }}

      - name: Get versions
        id: versions
        run: |
          echo "::set-output name=deno::v$(echo 'console.log(Deno.version.deno)' | deno run -)"
          HASH=${{ github.sha }}; echo "::set-output name=generator::${HASH:0:7}"

      - name: Generate a docset
        run: |
          deno run --allow-net --allow-write=deno.docset --allow-read --allow-run --no-check main.ts
          tar -cvzf Deno.tgz deno.docset

      - name: Create a tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag -a "${TAG_NAME}" -m "[CI] Automatically tagged via GitHub Actions"
          git push --tags
        env:
          TAG_NAME: ${{ github.event.inputs.deno_version || steps.versions.outputs.deno }}+${{ steps.versions.outputs.generator }}

      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.docset_version }}
          name: ${{ env.docset_version }}
          body: "[CI] Automatically released via GitHub Actions"
          files: Deno.tgz
          token: ${{ secrets.TOKEN }}
        env:
          docset_version: ${{ github.event.inputs.deno_version || steps.versions.outputs.deno }}+${{ steps.versions.outputs.generator }}
